from django.urls import path
from . import views

urlpatterns = [
    path("", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("courses/", views.course_list, name="course_list"),
    path("courses/create/", views.course_create, name="course_create"),
    path("courses/<int:pk>/update/", views.course_update, name="course_update"),
    path("courses/<int:pk>/delete/", views.course_delete, name="course_delete"),
    path("groups/", views.group_list, name="group_list"),
    path("groups/create/", views.group_create, name="group_create"),
    path("groups/<int:pk>/update/", views.group_update, name="group_update"),
    path("groups/<int:pk>/delete/", views.group_delete, name="group_delete"),
    path("groups/<int:pk>/extend/", views.group_extend, name="group_extend"),
    path("students/", views.student_list, name="student_list"),
    path("students/pending/", views.pending_students, name="pending_students"),
    path("students/create/", views.student_create, name="student_create"),
    path("students/<int:pk>/update/", views.student_update, name="student_update"),
    path("students/<int:pk>/delete/", views.student_delete, name="student_delete"),
    path("students/<int:pk>/profile/", views.student_profile, name="student_profile"),
    path("students/<int:pk>/freeze/", views.student_freeze, name="student_freeze"),
    path("students/<int:pk>/unfreeze/", views.student_unfreeze, name="student_unfreeze"),
    path("students/<int:pk>/remove/", views.student_remove_from_group, name="student_remove_from_group"),
    path("students/<int:pk>/add-to-group/", views.student_add_to_group, name="student_add_to_group"),
    path("groups/<int:pk>/detail/", views.group_detail, name="group_detail"),
    path("groups/<int:pk>/freeze/", views.group_freeze, name="group_freeze"),
    path("groups/<int:pk>/archive/", views.group_archive, name="group_archive"),
    path("groups/<int:pk>/close/", views.group_close, name="group_close"),
    path("groups/<int:pk>/settings/", views.group_settings, name="group_settings"),
    path("groups/<int:group_pk>/add-student/<int:student_pk>/", views.add_student_to_group, name="add_student_to_group"),
    path("groups/<int:group_pk>/remove-student/<int:student_pk>/", views.remove_student_from_group, name="remove_student_from_group"),
    path("statistics/", views.statistics, name="statistics"),
    path("surveys/", views.survey_list, name="survey_list"),
    path("surveys/create/", views.survey_create, name="survey_create"),
    path("surveys/<int:pk>/update/", views.survey_update, name="survey_update"),
    path("surveys/<int:pk>/delete/", views.survey_delete, name="survey_delete"),
]
